"""Add legal terms

Revision ID: 0937318016e8
Revises: e3f4a5b6c7d8
Create Date: 2026-06-18 21:12:54.582190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0937318016e8'
down_revision: Union[str, None] = 'e3f4a5b6c7d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tos_accepted_version', sa.String(), nullable=True))
    op.add_column('users', sa.Column('privacy_accepted_version', sa.String(), nullable=True))
    op.add_column('users', sa.Column('marketing_consent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'marketing_consent')
    op.drop_column('users', 'privacy_accepted_version')
    op.drop_column('users', 'tos_accepted_version')
    # ### end Alembic commands ###
