"""Add security columns

Revision ID: 6022fc235538
Revises: b2c3d4e5f6a7
Create Date: 2026-08-16 21:47:18.375530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6022fc235538'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('public_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_bills_public_id'), 'bills', ['public_id'], unique=True)
    op.create_index(op.f('ix_bills_user_id'), 'bills', ['user_id'], unique=False)
    op.add_column('users', sa.Column('public_id', sa.String(length=36), nullable=True))
    op.add_column('users', sa.Column('token_version', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('role', sa.String(), nullable=False))
    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.drop_column('users', 'role')
    op.drop_column('users', 'token_version')
    op.drop_column('users', 'public_id')
    op.drop_index(op.f('ix_bills_user_id'), table_name='bills')
    op.drop_index(op.f('ix_bills_public_id'), table_name='bills')
    op.drop_column('bills', 'public_id')
    # ### end Alembic commands ###
