"""Add image_filename to bills

Revision ID: b7d1a2f3c4e5
Revises: f3ad4ec381fe
Create Date: 2026-04-29 17:10:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7d1a2f3c4e5'
down_revision = 'f3ad4ec381fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'bills',
        sa.Column('image_filename', sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bills', 'image_filename')
    # ### end Alembic commands ###
