"""initial tables

Revision ID: f3ad4ec381fe
Revises: 
Create Date: 2026-04-12 23:54:23.184619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3ad4ec381fe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('du_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('du_name', sa.String(), nullable=False),
    sa.Column('rate_per_kwh', sa.Float(), nullable=False),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_du_rates_id'), 'du_rates', ['id'], unique=False)
    op.create_table('province_cooperatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('province', sa.String(), nullable=False),
    sa.Column('cooperative', sa.String(), nullable=False),
    sa.Column('location_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_province_cooperatives_id'), 'province_cooperatives', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('establishment_type', sa.String(), nullable=True),
    sa.Column('location_type', sa.String(), nullable=True),
    sa.Column('province', sa.String(), nullable=True),
    sa.Column('cooperative', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(), nullable=True),
    sa.Column('billing_period', sa.String(), nullable=True),
    sa.Column('du_name', sa.String(), nullable=True),
    sa.Column('kwh_consumed', sa.Float(), nullable=True),
    sa.Column('amount_due', sa.Float(), nullable=True),
    sa.Column('gen_charge', sa.Float(), nullable=True),
    sa.Column('transdel_charge', sa.Float(), nullable=True),
    sa.Column('system_loss_charge', sa.Float(), nullable=True),
    sa.Column('distsys_charge', sa.Float(), nullable=True),
    sa.Column('supplysys_charge', sa.Float(), nullable=True),
    sa.Column('mtrngsys_charge', sa.Float(), nullable=True),
    sa.Column('total_vat_charge', sa.Float(), nullable=True),
    sa.Column('prev_reading', sa.Float(), nullable=True),
    sa.Column('curr_reading', sa.Float(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('raw_ocr_text', sa.Text(), nullable=True),
    sa.Column('tips_json', sa.Text(), nullable=True),
    sa.Column('manually_corrected', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bills_id'), 'bills', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bills_id'), table_name='bills')
    op.drop_table('bills')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_province_cooperatives_id'), table_name='province_cooperatives')
    op.drop_table('province_cooperatives')
    op.drop_index(op.f('ix_du_rates_id'), table_name='du_rates')
    op.drop_table('du_rates')
    # ### end Alembic commands ###
