/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#260453",
        "on-primary": "#3a3000",
        "surface-container-lowest": "#12003b",
        "inverse-surface": "#e8ddff",
        "inverse-primary": "#705d00",
        "tertiary-container": "#634891",
        "primary-fixed-dim": "#e9c400",
        "on-secondary": "#362a50",
        "inverse-on-surface": "#371a7b",
        "on-tertiary": "#3c2068",
        "surface-container-low": "#21005e",
        "on-secondary-fixed": "#20143a",
        "on-surface": "#e8ddff",
        "error-container": "#93000a",
        "on-surface-variant": "#ccc3d5",
        "surface-dim": "#180048",
        "surface-tint": "#e9c400",
        "on-secondary-fixed-variant": "#4c4068",
        "on-primary-fixed": "#221b00",
        "outline": "#958e9e",
        "primary-fixed": "#ffe16d",
        "surface-container": "#260068",
        "tertiary": "#d5bbff",
        "secondary-container": "#4f426b",
        "secondary-fixed-dim": "#cfbfef",
        "surface-container-high": "#311075",
        "secondary-fixed": "#eaddff",
        "primary": "#e9c400",
        "surface": "#180048",
        "on-error-container": "#ffdad6",
        "secondary": "#cfbfef",
        "tertiary-fixed": "#ecdcff",
        "background": "#180048",
        "on-secondary-container": "#c1b1e0",
        "surface-bright": "#402584",
        "tertiary-fixed-dim": "#d5bbff",
        "on-background": "#e8ddff",
        "surface-variant": "#3c2080",
        "outline-variant": "#4a4453",
        "surface-container-highest": "#3c2080",
        "on-tertiary-container": "#d9c1ff",
        "primary-container": "#665500",
        "error": "#ffb4ab",
        "on-tertiary-fixed-variant": "#533880",
        "on-error": "#690005",
        "on-primary-container": "#efc900",
        "on-primary-fixed-variant": "#544600"
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif']
      },
    },
  },
  plugins: [],
}
